# Generated by Django 4.2.11 on 2025-06-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_camisetapedido_remove_detallepedido_camiseta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
