# Generated by Django 5.0.6 on 2025-06-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_aceptado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camiseta',
            old_name='tipo',
            new_name='calidad',
        ),
    ]
