# Generated by Django 5.0.6 on 2025-06-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_tipo_camiseta_calidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseño',
            name='precio',
        ),
    ]
