# Generated by Django 5.0.6 on 2025-07-02 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_diseño_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diseño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diseño')),
            ],
            options={
                'unique_together': {('cliente', 'diseño')},
            },
        ),
    ]
