# Generated by Django 5.0.6 on 2025-07-02 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diseño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.diseño')),
            ],
        ),
    ]
